### ISSUE TITLE
Replace Matlab's 'fmincon' on the cvnumerics

### ISSUE THREAD

**Issue by alexbuyval** [cureos/csnumerics#4]
Hi,

I am looking for C# library to replace 'fmincon' Matlab function in my application.
It seems that COBYLA is suitable for me. 
However, in my 'fmicon' solution I have got equality constraints as set functions like this:

```
function [c, ceq] = confun(x)
global at aw;
% Nonlinear inequality constraints
c = [];
% Nonlinear equality constraints
ceq = [x(1)-(at(3)+x(4)*(1-x(5)/x(6))+x(7)*x(8)/x(6));
       x(7)-(at(5)+x(9)*(1-x(10)/x(11)));
       aw(1)+aw(2)+aw(3)+aw(4)-at(1)-at(2)-at(3)-at(4)-at(5)-at(6)-x(4)-x(9)];
```

Can I use COBYLA in that case?
If so, is there any example how can I code it?

Best Regards,
Alex

**Comment by anders9ustafsson** [comment]
Hi Alex,

COBYLA as such only supports inequality constraints, _C_(**x**) &ge; 0, so you will need to formulate some kind of replacement constraint(s).

Assuming a non-equivalence tolerance of _&epsilon;_ you could replace _C_(**x**) = 0 with

_&epsilon;_ - |_C_(**x**)| &ge; 0

Best regards,
Anders @ Cureos

**Comment by alexbuyval** [comment]
Hi Anders,

Thank you for your quick answer!

I understood this idea.

How should I code these inequality constraints? Are there any examples?

Best Regards,
Alex

**Comment by anders9ustafsson** [comment]
Please look in the unit tests folders, you will find several usage examples there. For COBYLA, [here](https://github.com/cureos/csnumerics/blob/master/csnumerics.tests/Optimizers/CobylaTests.cs).

**Comment by alexbuyval** [comment]
Thank you! I will try.
